/**
 * FABOuanes OpenAPI Generated Type Definitions
 * Auto-generated by scripts/generate_openapi_ts.py
 */

export interface APIResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
}

export interface Body_api_upload_and_restore_backup_api_admin_backups_upload_restore_post {
  file: string;
}

export interface Body_bulk_import_client_history_api_v1_clients_import_history_bulk_post {
  file: string;
}

export interface Body_import_client_history_api_v1_clients_import_history_post {
  file: string;
  client_id?: string;
  force_reimport?: boolean;
}

export interface ErrorResponseSchema {
  success?: boolean;
  error: Record<string, unknown>;
}

export interface ExpenseCreateSchema {
  date: string;
  category?: string;
  description?: string;
  amount: number;
  payment_method?: string;
}

export interface ExpenseDetailResponse {
  success?: boolean;
  data: string;
}

export interface ExpenseOutSchema {
  date: string;
  category?: string;
  description?: string;
  amount: number;
  payment_method?: string;
  id: number;
}

export interface ExpenseUpdateSchema {
  date: string;
  category?: string;
  description?: string;
  amount: number;
  payment_method?: string;
}

export interface ExpensesListResponse {
  success?: boolean;
  data: unknown[];
  meta?: string;
}

export interface HTTPValidationError {
  detail?: unknown[];
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface PaymentCreate {
  client_id: number;
  amount: string;
  payment_type?: string;
  payment_date: string;
  sale_id?: string;
  raw_sale_id?: string;
  sale_kind?: string;
  notes?: string;
}

export interface PaymentCreateSchema {
  client_id: string;
  amount: string;
  payment_date?: string;
  payment_type?: string;
  sale_link?: string;
  notes?: string;
}

export interface ProductionCreateSchema {
  finished_product_id: number;
  output_quantity: string;
  production_date?: string;
  notes?: string;
  recipe_name?: string;
  save_recipe?: string;
  raw_material_id[]?: string;
  quantity[]?: string;
}

export interface ValidationError {
  loc: unknown[];
  msg: string;
  type: string;
  input?: string;
  ctx?: Record<string, unknown>;
}
